=== dromara/liteflow/liteflow-core/src/main/resources/dtd/liteflow.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!ELEMENT flow  ((nodes)? , (chain)*)>
<!ELEMENT nodes  (node)+>
<!ELEMENT node  (#PCDATA | EMPTY)*>
<!ELEMENT chain ((route)? | (body)? | #PCDATA)>
<!ELEMENT route (#PCDATA)>
<!ELEMENT body (#PCDATA)>

<!ATTLIST node
        id CDATA #REQUIRED
        name CDATA #IMPLIED
        type (script|boolean_script|switch_script|for_script) #IMPLIED
        class CDATA #IMPLIED
        file CDATA #IMPLIED
        language (qlexpress|groovy|js|python|lua|aviator|java|kotlin) #IMPLIED
        enable (true|false) #IMPLIED
        >
<!ATTLIST chain
        id CDATA #IMPLIED
        name CDATA #IMPLIED
        extends CDATA #IMPLIED
        enable (true|false) #IMPLIED
        namespace CDATA #IMPLIED
        thread-pool-executor-class CDATA #IMPLIED
        >

=== dromara/liteflow/liteflow-testcase-el/liteflow-testcase-el-script-javaxpro-springboot/src/test/resources/sameScript/flow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE flow PUBLIC  "liteflow" "liteflow.dtd">
<flow>
    <nodes>
        <!-- s1 和 s2 是完全相同的脚本内容，只是 nodeId 不同 -->
        <node id="s1" name="脚本S1" type="script" language="java">
            <![CDATA[
            import com.yomahub.liteflow.core.NodeComponent;
            import com.yomahub.liteflow.slot.DefaultContext;

            public class Demo extends NodeComponent {
                @Override
                public void process() throws Exception {
                    DefaultContext ctx = this.getFirstContextBean();
                    // 根据 nodeId 写入不同的数据来验证是否真的执行了对应节点
                    ctx.setData(this.getNodeId(), "executed by " + this.getNodeId());
                    System.out.println("Executing node: " + this.getNodeId());
                }
            }
            ]]>
        </node>

        <!-- s2 和 s1 的脚本内容完全相同 -->
        <node id="s2" name="脚本S2" type="script" language="java">
            <![CDATA[
            import com.yomahub.liteflow.core.NodeComponent;
            import com.yomahub.liteflow.slot.DefaultContext;

            public class Demo extends NodeComponent {
                @Override
                public void process() throws Exception {
                    DefaultContext ctx = this.getFirstContextBean();
                    // 根据 nodeId 写入不同的数据来验证是否真的执行了对应节点
                    ctx.setData(this.getNodeId(), "executed by " + this.getNodeId());
                    System.out.println("Executing node: " + this.getNodeId());
                }
            }
            ]]>
        </node>

        <!-- a1, a2, a3 三个节点也是完全相同的脚本 -->
        <node id="a1" name="脚本A1" type="script" language="java">
            <![CDATA[
            import com.yomahub.liteflow.core.NodeComponent;
            import com.yomahub.liteflow.slot.DefaultContext;

            public class AnotherDemo extends NodeComponent {
                @Override
                public void process() throws Exception {
                    DefaultContext ctx = this.getFirstContextBean();
                    ctx.setData(this.getNodeId(), "data from " + this.getNodeId());
                    System.out.println("Node " + this.getNodeId() + " is working");
                }
            }
            ]]>
        </node>

        <node id="a2" name="脚本A2" type="script" language="java">
            <![CDATA[
            import com.yomahub.liteflow.core.NodeComponent;
            import com.yomahub.liteflow.slot.DefaultContext;

            public class AnotherDemo extends NodeComponent {
                @Override
                public void process() throws Exception {
                    DefaultContext ctx = this.getFirstContextBean();
                    ctx.setData(this.getNodeId(), "data from " + this.getNodeId());
                    System.out.println("Node " + this.getNodeId() + " is working");
                }
            }
            ]]>
        </node>

        <node id="a3" name="脚本A3" type="script" language="java">
            <![CDATA[
            import com.yomahub.liteflow.core.NodeComponent;
            import com.yomahub.liteflow.slot.DefaultContext;

            public class AnotherDemo extends NodeComponent {
                @Override
                public void process() throws Exception {
                    DefaultContext ctx = this.getFirstContextBean();
                    ctx.setData(this.getNodeId(), "data from " + this.getNodeId());
                    System.out.println("Node " + this.getNodeId() + " is working");
                }
            }
            ]]>
        </node>
    </nodes>

    <!-- chain1: 测试两个相同脚本的节点 -->
    <chain name="chain1">
        THEN(s1, s2);
    </chain>

    <!-- chain2: 测试三个相同脚本的节点 -->
    <chain name="chain2">
        THEN(a1, a2, a3);
    </chain>
</flow>

=== dromara/liteflow/liteflow-testcase-el/liteflow-testcase-el-react-agent/src/test/resources/agent/flow.el.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE flow PUBLIC "liteflow" "liteflow.dtd">
<flow>

    <!-- ============== 基础链路：单 Agent + prepare/record ============== -->
    <chain name="basicAgentChain">
        THEN(preparePrompt, basicAgent, recordReply);
    </chain>

    <!-- ============== 自定义 handleReply 的 Agent ============== -->
    <chain name="customHandleReplyChain">
        THEN(preparePrompt, customHandleReplyAgent, recordReply);
    </chain>

    <!-- ============== 多 Agent 在同一条 THEN 链 ============== -->
    <chain name="multiAgentChain">
        THEN(preparePrompt, multiAgentA, multiAgentB, recordReply);
    </chain>

    <!-- ============== WHEN 并发执行多 Agent ============== -->
    <chain name="whenParallelChain">
        THEN(
            preparePrompt,
            WHEN(parallelAgentA, parallelAgentB).maxWaitSeconds(120),
            recordReply
        );
    </chain>

    <!-- ============== IF 路由分支 ============== -->
    <chain name="ifRoutingChain">
        THEN(
            preparePrompt,
            IF(isMathRequest, mathBranchAgent, defaultBranchAgent),
            recordReply
        );
    </chain>

    <!-- ============== 自定义工具的 Agent ============== -->
    <chain name="customToolChain">
        THEN(preparePrompt, customToolAgent, recordReply);
    </chain>

    <!-- ============== 流式事件 ============== -->
    <chain name="streamingChain">
        THEN(preparePrompt, streamingAgent, recordReply);
    </chain>

    <!-- ============== Hook 注册 ============== -->
    <chain name="hookChain">
        THEN(preparePrompt, hookAgent, recordReply);
    </chain>

    <!-- ============== maxIterations 覆写 ============== -->
    <chain name="maxIterationsChain">
        THEN(preparePrompt, maxIterationsAgent, recordReply);
    </chain>

    <!-- ============== Workspace 文件工具 ============== -->
    <chain name="workspaceToolsChain">
        THEN(preparePrompt, workspaceToolsAgent, recordReply);
    </chain>

    <!-- ============== Shell 工具 ============== -->
    <chain name="shellToolsChain">
        THEN(preparePrompt, shellToolsAgent, recordReply);
    </chain>

    <!-- ============== Skills 加载 ============== -->
    <chain name="skillsChain">
        THEN(preparePrompt, skillsAgent, recordReply);
    </chain>

    <!-- ============== 会话连续性 / agentKey 自定义 ============== -->
    <chain name="memoryChain">
        THEN(preparePrompt, memoryAgent, recordReply);
    </chain>

    <chain name="customAgentKeyChain">
        THEN(preparePrompt, customAgentKeyAgent, recordReply);
    </chain>

    <chain name="resolveCidChain">
        THEN(preparePrompt, resolveCidAgent, recordReply);
    </chain>

    <!-- ============== buildModel 逃生舱 ============== -->
    <chain name="buildModelEscapeChain">
        THEN(preparePrompt, buildModelEscapeAgent, recordReply);
    </chain>

</flow>

=== dromara/liteflow/liteflow-testcase-el/liteflow-testcase-el-react-agent/src/test/resources/agent/connectivity/flow.el.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE flow PUBLIC "liteflow" "liteflow.dtd">
<flow>
    <!-- 每个平台一个 chain，链路统一为 THEN(prepare, <platform>Agent, record)。 -->

    <chain name="openaiChain">
        THEN(preparePrompt, openaiAgent, recordReply);
    </chain>

    <chain name="anthropicChain">
        THEN(preparePrompt, anthropicAgent, recordReply);
    </chain>

    <chain name="geminiChain">
        THEN(preparePrompt, geminiAgent, recordReply);
    </chain>

    <chain name="dashscopeChain">
        THEN(preparePrompt, dashscopeAgent, recordReply);
    </chain>

    <chain name="deepseekChain">
        THEN(preparePrompt, deepseekAgent, recordReply);
    </chain>

    <chain name="kimiChain">
        THEN(preparePrompt, kimiAgent, recordReply);
    </chain>

    <chain name="glmChain">
        THEN(preparePrompt, glmAgent, recordReply);
    </chain>

    <chain name="minimaxChain">
        THEN(preparePrompt, minimaxAgent, recordReply);
    </chain>

    <chain name="openaiCompatibleCustomChain">
        THEN(preparePrompt, openaiCompatibleCustomAgent, recordReply);
    </chain>

    <chain name="anthropicCompatibleChain">
        THEN(preparePrompt, anthropicCompatibleAgent, recordReply);
    </chain>
</flow>

=== dromara/liteflow/liteflow-testcase-el/liteflow-testcase-el-springboot/src/test/resources/booleanOpt/flow.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE flow PUBLIC  "liteflow" "liteflow.dtd">
<flow>
    <chain name="chain1">
        IF(AND(x1, x2, x3), a, b);
    </chain>

    <chain name="chain2">
        IF(OR(x1, x2, x3), a, b);
    </chain>

    <chain name="chain3">
        IF(AND(x1, x2, NOT(x3)), a, b);
    </chain>

    <chain name="chain4">
        IF(
            OR(
                AND(x1, x3), NOT(OR(x3, x4))
            ),
            a, b
        );
    </chain>

    <chain name="chain5">
        WHILE(AND(w1, NOT(w2))).DO(a).BREAK(bk);
    </chain>

    <chain name="chain6">
        IF(AND(NOT(x1), x2, x3), a, b);
    </chain>

    <chain name="chain7">
        IF(OR(x3,x4,x5), a, b);
    </chain>

</flow>
